import time
import numbers

def intro():
    print("Hello, " + name + ". Are you ready to being the " + name + "'s parable? (y/n)")
    begin = input()
    begin = begin.lower()
    if begin == 'y':
        print("This is a story of a man named " + name + ". He works for a company. He loves his work, his coworkers, and his company.")
        time.sleep(7)
        print("One day, he goes to his workspace, just as other days. All of his coworkers are gone. What happened to them?")
        time.sleep(5)
        print(name + " decides to meet his boss.")
        time.sleep(3) #delay before room()
        room()
    elif begin == 'n':
        print("You coward! You'll never be able to make decision in your life!")
        time.sleep(3)
        exit()
    else:
        print("Please type y or n")
        intro()

def room(): #First room
    print("You are in a room with two doors. Which door are you heading?")
    choice = input("Left? or Right? (l/r)")
    choice = choice.lower()
    if choice == 'l':
        choice_left()
    elif choice == "r":
        choice_right()
    else:
        print("Please type l or r.")
        room()

def choice_left(): #left room aka conference room
    print("A huge conference room with no one in here. Where is everyone?")
    time.sleep(5)
    print("You can make another choice here; you can either head to the boss's room or go back to your room.")
    time.sleep(6)
    choice2 = input("Are you going to the boss's room? (y/n)")
    choice2 = choice2.lower()
    if choice2 == "y":
        choice_boss()
    elif choice2 == "n":
        choice_badend()
    else:
        print("Please type y or n.")
        choice_left()
        
def choice_boss():
    print("You see a huge room with comfortable sofa. You feel something suspicious from the left wall.")
    time.sleep(5)
    print("Oh, you found a keypad behind the boss's place. Of course, you will never know the password is '8460'.")
    time.sleep(6)
    numguess()
    
def numguess():
    print("You decided to type some random number.(Four digit number)")
    guess = input()
#    guess = int(guess)
    if guess != "8460":
        print("Of course, you don't know the password is '8460.' You should guess it better.")
        numguess()
    elif guess == "8460":
        print("Oh! You somehow guessed a password for the secret room. You are so lucky!")
        time.sleep(5)
        secretdoor()

def secretdoor():
    print("You opened the secret door to the secret place.")
    time.sleep(5)
    print("In front of you, there is an elavator with two buttons : up or down")
    time.sleep(5)
    print("You feel like you need to go upward to meet with your boss.")
    time.sleep(5)
    elevator()

def elevator():
    choice3 = input("So, you pressed the button to... (up/down)")
    choice3 = choice3.lower()
    if choice3 == "up":
        print("Soon, elavator arrived...")
        time.sleep(3)
        upfloor()
    elif choice3 == "down":
        print("Soon, elavator arrived...")
        time.sleep(3)
        downfloor()
    else:
        print("Please type up or down.")
        elevator()

def upfloor():
    print("The elavator headed to upward. The door opens and soon you see a facility with giant door.")
    time.sleep(5)
    print("On the top of the door there is a label : MIND CONTROL FACILITY")
    time.sleep(5)
    print("You decided to open the door.")
    time.sleep(4)
    print("A huge screen was filled with all of the workers in the company, include " + name + " and his coworkers...")
    time.sleep(6)
    print("with small labels under the workers; mindcontrol status : on")
    time.sleep(4)
    print("Was " + name + " mind controlled by boss? Were his coworkers? " + name + " started to realize that his work is not what he wanted to do.")
    time.sleep(7)
    print("Now, " + name + " is standing in front of the mind controll facility. You can turn the facility off.")
    time.sleep(5)
    mindcontrol()
    
def mindcontrol():
    print("It is time to decide. You move your hand to the control module and turn...(on/off)")
    choice4 = input()
    choice4 = choice4.lower()
    if choice4 == "on":
        mindcontrol_on()
    elif choice4 == "off":
        escape_end()
    else:
        print("Please type on or off.")
        
def mindcontrol_on():
    print("Instead of turning off the facility, " + name + " decided to be the owner of the facility...")
    time.sleep(5)
    print("did not know the fact that it was trap. A counter for the explosion of the entire facility started.")
    time.sleep(5)
    print("NOW, YOU HAVE 60 SECONDS. DO SOMETHING OR WAIT UNTIL YOU DIE.")
    time.sleep(3)
    mindinput()
    
def mindinput(): #explosion end
    minutecount = 0
    while minutecount < 60:
        minutecount = minutecount + 1
        time.sleep(1)
        print(minutecount, "sec elapsed")
    print("Good bye, " + name + ". You died without solving the mystery of the company.")
    time.sleep(3)

def escape_end(): #escape end
    print("You turned off the power for the entire facility. The building is collasping in..")
    time.sleep(3)
    print("Three")
    time.sleep(1)
    print("Two")
    time.sleep(1)
    print("One")
    time.sleep(1)
    print("Joking. You are now free to go. The emergency door behind you is opened.")
    time.sleep(5)
    print("But, don't you wanna know what happened to your boss and coworkers?")
    time.sleep(5)
    print("Go back, turn this game again, and make other decisions.")
    time.sleep(4)
    print("See how your decisions change the story. Because it is 'your' parable.")
    time.sleep(5)

def downfloor():
    print("The elavator headed to downward. The door opens and there is only darkness in front of you.")
    time.sleep(5)
    print("You can't even see your feet, because there is no light in this floor. Suddenly you feel wind blows.")
    time.sleep(6)
    print("It is not safe to proceed, but you also want to know the boss's secret.")
    time.sleep(5)
    choice = input("So, you decided to...(back/proceed) ")
    choice = choice.lower()
    if choice == "back":
        print("Yeah, probably you should go upwards")
        time.sleep(4)
        upfloor()
    elif choice == "proceed":
        print("'Whatever, there should be nothing dangerous in company building', you said")
        time.sleep(5)
        darkness()
def darkness():
    print("The place is really dark. You don't have any light source to use. Once you left the elavator, the elavator closed.")
    time.sleep(6)
    print("You try to feel the wind, and walk to where the wind blows.")
    time.sleep(5)
    print("You reach the wall, and find a light switch. You turn the switch on.")
    time.sleep(5)
    print("Huge wall is surrounding you. On the left end, you find a picture looks like maze with message:")
    time.sleep(5)
    print("'Greeting, traveler! Almighty power has guided you to this sacred shrine. To gain such power, you traveler should go across this maze.'")
    time.sleep(6)
    maze()

def maze():
    print("entrance")
    print("┌ ┬─────────┬───┐  ")
    print("│ │ ┌─────╴ │ ╶─┤")
    print("│ ╵ │ ┌─────┤ ╷ │  ")
    print("├───┤ └───┐ ╵ │ │")
    print("│ ┌─┴───┐ └───┘ │ ")
    print("│ ╵ ┌─┐ └───┬─╴ │ ")
    print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
    print("├─────╴ │ ╵ ╶─┘ │ ")
    print("└  ─────┴───────┘")
    print("exit")
    time.sleep(3)
    print("You decide to solve the maze. To solve the maze, you should make 'a lot of' decisions.")
    time.sleep(5)
    print("In this puzzle, you will make decision with 'l', 'r', 'u', 'd', which are left, right, up, down.")
    time.sleep(5)
    print("Star(*) will indicate your current position. Ready?")
    time.sleep(4)
    maze_1()
    
def maze_1():
    maze= input("So, your first choice is...(l/r/u/d) ")
    maze = maze.lower()
    if maze == "d":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│*╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        maze_2()
    else:
        print("You cannot move that direction.")
        maze_1()
        
def maze_2():
    maze2 = input("On the corner, you are moving to...(l/r/u/d) ")
    maze2 = maze2.lower()
    if maze2 != "r":
        print("You cannot move that direction.")
        maze_2()
    else:
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵*│ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        maze_3()
def maze_3():
    maze3 = input("On the corner, you are moving to...(l/r/u/d) ")
    maze3 = maze3.lower()
    if maze3 != "r":
        print("You cannot move that direction.")
        maze_3()
    else:
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴*│ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        maze_4()
def maze_4():
    maze4 = input("On the corner, you are moving to...(l/r/u/d) ")
    maze4 = maze4.lower()
    if maze4 != "d":
        print("You cannot move that direction.")
        maze_4()
    else:
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐*└───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        maze_6()
def maze_6():
    maze6 = input("You follow the path, and find the first crossroad. You are moving to(l/r/u/d) ")
    maze6 = maze6.lower()
    if maze6 == "r":
        print("You cannot move that direction.")
        maze_6()
    elif maze6 == "l":
        print("You don't need to go back.")
        maze_6()
    elif maze6 == "u":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤*╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        maze_7()
    else:
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘*┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        maze_8()
def maze_7():
    print("From now on, you can move backward. Just letting you know...")
    time.sleep(3)
    maze7 = input("On the corner, you are moving to...(l/r/u/d) ")
    maze7 = maze7.lower()
    if maze7 == "l":
        print("You cannot move that direction.")
        maze_7()
    elif maze7 == "u":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │*╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        time.sleep(3)
        print("You are at dead end. Going back...")
        time.sleep(3)
        maze_7()
    elif maze7 == "d":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐*╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        time.sleep(3)
        print("You are at dead end. Going back...")
        time.sleep(3)
        maze_7()    
    else:
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐*└───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        time.sleep(3)
        print("You just returned to the previous crossroad.")
        time.sleep(3)
        maze_6()
def maze_8():
    print("From now on, you can move backward. Just letting you know...")
    time.sleep(3)
    maze8 = input("You follow the path, and find a crossroad. You are moving to(l/r/u/d) ")
    maze8 = maze8.lower()
    if maze8 == "d":
        print("You cannot move that direction.")
        maze_8()
    elif maze8 == "r":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘*│ ")
        print("└  ─────┴───────┘")
        print("exit")
        time.sleep(3)
        print("You are at dead end. Going back...")
        time.sleep(3)
        maze_8()
    elif maze8 == "u":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐*└───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        time.sleep(3)
        print("You just returned to the previous crossroad.")
        time.sleep(3)
        maze_6()
    else:
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵*┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        maze_9()
def maze_9():
    maze9 = input("You follow the path, and find a crossroad. You are moving to(l/r/u/d) ")
    maze9 = maze9.lower()
    if maze9 == "l":
        print("You cannot move that direction.")
        maze_9()
    elif maze9 == "u":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│*┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        time.sleep(3)
        print("You are at dead end. Going back...")
        time.sleep(3)
        maze_9()
    elif maze9 == "r":
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘*┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└  ─────┴───────┘")
        print("exit")
        time.sleep(3)
        print("You just returned to the previous crossroad.")
        time.sleep(3)
        maze_8()
    else:
        print("entrance")
        print("┌ ┬─────────┬───┐  ")
        print("│ │ ┌─────╴ │ ╶─┤")
        print("│ ╵ │ ┌─────┤ ╷ │  ")
        print("├───┤ └───┐ ╵ │ │")
        print("│ ┌─┴───┐ └───┘ │ ")
        print("│ ╵ ┌─┐ └───┬─╴ │ ")
        print("│ ╶─┘ └─┐ ┌─┘ ┌─┤")
        print("├─────╴ │ ╵ ╶─┘ │ ")
        print("└ * ────┴───────┘")
        print("exit")
        maze_finish()
        
def maze_finish():
    print("Congratulation! You solved the maze!")
    time.sleep(4)
    print("You see an office door in front of the maze. On the door, it says 'employee only'.")
    time.sleep(5)
    print("'Whatever, I am employee of this company', you think. You open the door.")
    time.sleep(5)
    print("And there are...")
    time.sleep(2.5)
    print("all of his coworkers in the room! Even his boss was in there. Everyone is fall asleep, or fainted.")
    time.sleep(5)
    print("On the table, you see a laptop with terminal turned on, says 'awaiting input...'")
    time.sleep(5)
    print("'Oh, it is waiting for someone to operate something. I will be the one, why not?' you said.")
    time.sleep(5)
    print("So, you type your name, " + name + ", in terminal. Suddenly, some texts appear on the screen:")
    time.sleep(5)
    print("HELLO, " + name + ". INITIATING MIND CONTROL FACILITY...")
    time.sleep(4)
    print("Yeah, you just turned on the mind control facility. You will be the only one not affected by it!")
    time.sleep(5)
    print("Now, you own the company! Congrtulations!")
    time.sleep(4)
    print("You don't need to work with your arrogant coworkers, your boss, and even your family!")
    time.sleep(5)
    print("You will stay in the company forever, as boss. FOREVER...")
    time.sleep(4)
    print("And " + name + " lived in the company. Happily ever after, Forever...")
    time.sleep(5)
###-------------------------right door-------------------------------###
def choice_right():
    print("You know this is not the right way to go to the boss's room. Probably just want to hang out in the lounge?")
    time.sleep(5)
    print("Anyway, you enter the lounge and stay for a while, with a cup of coffee.")
    time.sleep(15)
    print("That's enough! Let's get back to work. In order to go to the boss's room, you need to go past the left room on the other side.")
    time.sleep(6)
    choice5 = input("So, you walk to the...(front/left) door.")
    choice5 = choice5.lower()
    if choice5 == "front":
        choice_front()
    elif choice5 == "left":
        print("Yeah, " + name + " is a good employee, knows how to make 'decisions'. You headed to the boss's room")
        time.sleep(5)
        choice_boss()
    else:
        print("Please type front or left.")

def choice_front():
    print("Oh, god. You are such a bad employee. Everyone wonders how you did not get fired before.")
    time.sleep(5)
    print("Seriously, you should either go back to your place or go to your boss's room.")
    time.sleep(5)
    print("Anyway, you enter a room filled with construction material. A lot of stuffs are piled from bottom of the warehouse.")
    time.sleep(5)
    print("Hey, you have nothing to do here. Don't ever try to climb the material, because there is nothing in the door up there.")
    time.sleep(6)
    print("It is just room for private--no, nono forget about it. ANYWAY, that room is nothing.")
    time.sleep(5)
    choice6 = input("Yeah, " + name + " is a good employee, so you headed...(up/back)")
    choice6 = choice6.lower()
    if choice6 == "up":
        print("Wow, I warned you. It is NOTHING.")
        time.sleep(5)
        uproom()
    elif choice6 == "back":
        print("Of course. " + name + " is a good employee. Now, you will go straight to your boss's room.")
        time.sleep(5)
        choice_boss()
    else:
        print("Please type up or back.")

def uproom():
    print(name + " starts to climb up the pile of building material. Isn't it dangerous work for an officeworker?")
    time.sleep(5)
    print("Anyway, you climb up to the half of the pile. Yeah, it is indeed too dangerous for you, especially without helmet.")
    time.sleep(6)
    print("Probably something from top would fall to your head and kill you...?")
    time.sleep(5)
    print("Oh, I should've not say that. Suddendly, a steel bar drops from the top, and hit " + name + "'s head.")
    time.sleep(5)
    print(name + " drop from the pile and hit his head with ground so hard. Oh...poor "+ name + ".")
    time.sleep(5)
    print("Your curiousness kills yourself. In addition, I did not tell lie. The room is just a private space for boss...")
    time.sleep(6)
    print("and that door up there is BLOCKED, of course. Who would use the door in the warehouse?")
    time.sleep(5)
    print("Seriously, you should learn how to follow others. If you listened to me, you would not kill yourself.")
    time.sleep(5)
    print("Turn off the game using ctrl+c, turn on again, and make another 'proper' decision. Please.")
    time.sleep(5)
    print("The game will not finish by itself, so please go for it.")
    time.sleep(600)
    print("Wow, so you waited for 10 minutes to see this string. Congrats. You win. The game will finish by itself. Go away.")
    time.sleep(5)

def choice_badend():
    print(name + " is so afraid of meeting with his boss, that he might get fire " + name + " because you left your office during worktime.")
    time.sleep(7)
    print("Rather than go ask about the situation, " + name + " decides to wait in his room.")
    time.sleep(5)
    print("You waited, waited, and waited. You have no idea how much time has passed since then. Probably a day? a week? a month?")
    time.sleep(5)
    print("I am not blaming you. It is not your fault, right? You did what you supposed to do, and it is better to be safe, always.")
    time.sleep(6)
    print("So, " + name + " lived in " + name + "'s office forever, happily ever after...")
    time.sleep(5)

while True:
    playcount = 0
    while playcount < 1:
        playcount = playcount + 1
        print("Welcome to 'your' adventure! You are going to make some 'decisions' in this text-based game.")
        name = input("What is your name? ")
        intro()
        print("The end is not the end...")
        time.sleep(5)
    while playcount == 1:
        playcount = playcount + 1
        print("This game is restarting endlessly, because the end is not 'the end'")
        time.sleep(5)
        print("You can always quit this game by answering 'n' to the first question or using ctrl+c command.")
        time.sleep(5)
        intro()
        print("The end is not the end...")
        time.sleep(5)
    while playcount < 10:
        playcount = playcount + 1
        intro()
        print("The end is not the end...")
        time.sleep(5)
    while playcount >= 10:
        print("Wow, you have been playing " + name +"'s parable for", playcount, "in a row!")
        playcount = playcount + 1
        intro()
        print("The end is not the end...")
        time.sleep(5)